version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm install
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run unit Tests
          command: npm run test:unit
      - run:
          name: build to deploy
          command: npm run build
          
orbs:
  cypress: cypress-io/cypress@1
  heroku: circleci/heroku@1.2

workflows:
  orb-free-workflow:
    jobs:
      - test
      - cypress/run:
         name: e2e Tests
         requires:
            - test # only run deploy-via-git job if the build job has completed
      - heroku/deploy-via-git:
          force: true # this parameter instructs the push to use a force flag when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git
          requires:
            - e2e Tests # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master